# shellcheck shell=bash
# Swarm file-config sync: hash-versioned docker configs for services labeled
# eip.config.sync=1. Discovery via eipconfig (yaml.v3).
# Callers: stack-deploy / update-data (overlay), swarm-sync / release (apply).

_EIP_CONFIGS_LIB="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=log.sh
source "${_EIP_CONFIGS_LIB}/log.sh"
# shellcheck source=paths.sh
source "${_EIP_CONFIGS_LIB}/paths.sh"
# shellcheck source=require.sh
source "${_EIP_CONFIGS_LIB}/require.sh"
# shellcheck source=eip-config.sh
source "${_EIP_CONFIGS_LIB}/eip-config.sh"

# Content hash (12 hex chars) of a host file. Raw bytes — no normalization.
eip_config_file_hash() {
  local file="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "${file}" | awk '{ print substr($1, 1, 12) }'
  else
    shasum -a 256 "${file}" | awk '{ print substr($1, 1, 12) }'
  fi
}

eip_config_object_name() {
  local key="$1" hash="$2"
  printf 'eip_%s_%s' "${key}" "${hash}"
}

# Ensure docker config object exists for file contents. Prints object name.
eip_ensure_config_object() {
  local key="$1" file="$2" dry="${3:-0}"
  local hash obj
  hash="$(eip_config_file_hash "${file}")"
  obj="$(eip_config_object_name "${key}" "${hash}")"
  if docker config inspect "${obj}" >/dev/null 2>&1; then
    printf '%s' "${obj}"
    return 0
  fi
  if [ "${dry}" -eq 1 ]; then
    echo "dry-run: would create docker config ${obj} (from ${file})" >&2
    printf '%s' "${obj}"
    return 0
  fi
  if ! docker config create "${obj}" "${file}" >/dev/null; then
    echo "Error: failed to create docker config ${obj}" >&2
    return 1
  fi
  echo "created docker config ${obj}" >&2
  printf '%s' "${obj}"
}

# Drop older eip_<key>_* objects that are not keep (best-effort).
eip_prune_old_config_objects() {
  local key="$1" keep="$2"
  local name
  while IFS= read -r name; do
    [ -n "${name}" ] || continue
    [ "${name}" = "${keep}" ] && continue
    if docker config rm "${name}" >/dev/null 2>&1; then
      echo "pruned superseded docker config ${name}" >&2
    fi
  done < <(docker config ls --format '{{.Name}}' 2>/dev/null | grep -E "^eip_${key}_" || true)
}

# Discover managed mounts. Prints: key<TAB>file<TAB>service<TAB>target
# Optional args: stack fragment paths (default data + obs).
discover_config_sync() {
  local files=("$@") f abs
  if [ "${#files[@]}" -eq 0 ]; then
    files=("${DATA_STACK_FILE}")
    if [ -f "$(eip_stack_abs "${OBS_STACK_FILE}")" ]; then
      files+=("${OBS_STACK_FILE}")
    fi
  fi
  for f in "${files[@]}"; do
    abs="$(eip_stack_abs "${f}")"
    require_file "${abs}" || return 1
    eipconfig_run_raw discover-config-sync --stack "${abs}" || return 1
  done
}

# Remove top-level configs: block from an expanded stack file (overlay supplies objects).
eip_strip_stack_configs_block() {
  local file="$1" tmp
  tmp="$(mktemp)"
  awk '
    /^configs:[[:space:]]*$/ { skip = 1; next }
    skip && /^[A-Za-z0-9_-]+:/ { skip = 0 }
    skip && /^x-/ { skip = 0 }
    skip { next }
    { print }
  ' "${file}" >"${tmp}"
  mv "${tmp}" "${file}"
}

# Append -c SWARM_CONFIGS_FILE onto a named array when the overlay exists.
# Usage: CONFIG_ARGS=(); eip_append_swarm_configs_args CONFIG_ARGS
eip_append_swarm_configs_args() {
  local -n _eip_cfg_args="$1"
  if [ -f "${SWARM_CONFIGS_FILE}" ]; then
    _eip_cfg_args+=(-c "${SWARM_CONFIGS_FILE}")
  fi
}

# Create hashed config objects + write SWARM_CONFIGS_FILE overlay.
# Usage: sync_swarm_configs [--dry-run]
sync_swarm_configs() {
  local dry=0
  case "${1:-}" in
    --dry-run|-n) dry=1 ;;
  esac

  require_file "$(eip_stack_abs "${DATA_STACK_FILE}")" || return 1

  local clean key file service target obj missing=0
  clean="$(mktemp)"

  while IFS=$'\t' read -r key file service target; do
    [ -n "${key}" ] || continue
    if [ ! -f "${file}" ]; then
      echo "Error: config file missing for ${key}: ${file}" >&2
      missing=1
      continue
    fi
    if grep -q "^${key}	" "${clean}" 2>/dev/null; then
      continue
    fi
    obj="$(eip_ensure_config_object "${key}" "${file}" "${dry}")" || {
      rm -f "${clean}"
      return 1
    }
    printf '%s\t%s\n' "${key}" "${obj}" >>"${clean}"
  done < <(discover_config_sync)

  if [ "${missing}" -ne 0 ]; then
    rm -f "${clean}"
    return 1
  fi

  if [ "${dry}" -eq 1 ]; then
    echo "dry-run: would write ${SWARM_CONFIGS_FILE}" >&2
    if [ -s "${clean}" ]; then
      cat "${clean}" >&2
    else
      echo "(no eip.config.sync services)" >&2
    fi
    rm -f "${clean}"
    return 0
  fi

  if [ ! -s "${clean}" ]; then
    rm -f "${SWARM_CONFIGS_FILE}" "${clean}"
    eip_vlog "No eip.config.sync services — skipped ${SWARM_CONFIGS_FILE}"
    return 0
  fi

  {
    echo "# Generated by sync_swarm_configs — do not edit."
    echo "# Logical names match service configs: source; objects are content-hashed."
    echo "configs:"
    sort -t "$(printf '\t')" -k1,1 "${clean}" | while IFS=$'\t' read -r key obj; do
      [ -n "${key}" ] || continue
      echo "  ${key}:"
      echo "    external: true"
      echo "    name: ${obj}"
    done
  } >"${SWARM_CONFIGS_FILE}"
  eip_vlog "Wrote ${SWARM_CONFIGS_FILE}"
  rm -f "${clean}"
}

# Apply hash-diff config mounts to running services (no full stack rematerialize).
# Usage: apply_swarm_configs [--dry-run]
apply_swarm_configs() {
  local dry=0
  case "${1:-}" in
    --dry-run|-n) dry=1 ;;
  esac

  require_docker || return 1
  require_file "$(eip_stack_abs "${DATA_STACK_FILE}")" || return 1

  local key file service target hash obj live_name swarm_svc updated=0 skipped=0 missing_svc=0

  while IFS=$'\t' read -r key file service target; do
    [ -n "${key}" ] || continue
    if [ ! -f "${file}" ]; then
      echo "Error: config file missing for ${key}: ${file}" >&2
      return 1
    fi
    hash="$(eip_config_file_hash "${file}")"
    obj="$(eip_config_object_name "${key}" "${hash}")"
    swarm_svc="${STACK_NAME}_${service}"

    if ! docker service inspect "${swarm_svc}" >/dev/null 2>&1; then
      echo "skip ${swarm_svc} (not deployed; config ${key})"
      missing_svc=$((missing_svc + 1))
      continue
    fi

    live_name="$(docker service inspect "${swarm_svc}" --format '{{range .Spec.TaskTemplate.ContainerSpec.Configs}}{{.ConfigName}}	{{if .File}}{{.File.Name}}{{end}}{{"\n"}}{{end}}' 2>/dev/null \
      | awk -F '\t' -v tgt="${target}" '$2 == tgt { print $1; exit }')"
    if [ -z "${live_name}" ]; then
      live_name="$(docker service inspect "${swarm_svc}" --format '{{range .Spec.TaskTemplate.ContainerSpec.Configs}}{{.ConfigName}}{{"\n"}}{{end}}' 2>/dev/null \
        | grep -E "^eip_${key}(_[a-f0-9]+)?$" | head -n1 || true)"
    fi

    if [ "${live_name}" = "${obj}" ]; then
      echo "unchanged ${swarm_svc} (config ${key})"
      skipped=$((skipped + 1))
      continue
    fi

    echo "plan ${swarm_svc}: config ${key}: ${live_name:-"(none)"} -> ${obj}"
    if [ "${dry}" -eq 1 ]; then
      echo "dry-run: would ensure ${obj} and service update ${swarm_svc}"
      updated=$((updated + 1))
      continue
    fi

    eip_ensure_config_object "${key}" "${file}" 0 >/dev/null || return 1

    local args=(service update --detach=true)
    if [ -n "${live_name}" ]; then
      args+=(--config-rm "${live_name}")
    fi
    args+=(--config-add "source=${obj},target=${target}" "${swarm_svc}")
    if ! docker "${args[@]}"; then
      echo "Error: failed to update configs on ${swarm_svc}" >&2
      return 1
    fi
    echo "updated ${swarm_svc} (config ${key})"
    eip_prune_old_config_objects "${key}" "${obj}" || true
    if [ "${live_name}" = "eip_${key}" ]; then
      docker config rm "eip_${key}" >/dev/null 2>&1 || true
    fi
    updated=$((updated + 1))
  done < <(discover_config_sync)

  echo "config sync apply: updated=${updated} unchanged=${skipped} not_deployed=${missing_svc}"
}
